meta_name: "Capybara"
meta_title: "Capybara - Partagez, économisez, vivez mieux avec Capybara !"
meta_description: "Partage d'objets ménagers, outils et articles de jardinage."
meta_image: "Logo_Capy_3-removebg-preview.png" # should exist in `app/assets/images/`
